//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineAptitudeTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AptiClear
    {
        public int ClearID { get; set; }
        public int CandidateID { get; set; }
        public string FullName { get; set; }
        public Nullable<int> TotalScore { get; set; }
        public Nullable<System.DateTime> TransferDate { get; set; }
    }
}
